seed: 42
resume: False
resume_epoch: 5
trainer:
  model_name: 'ResNetClassifier'
  device: 'mps'
  nm_epochs: 100
  test_every: 5
  save_every: 5
  LOG_PATH: './logs'  # Path to save model logs
  ResNetClassifier:
    pretrained: True
    nm_markers: ???
    nm_classes: 2
  VisionTransformer:
    pretrained: True
    nm_markers: ???
    nm_classes: 2
  optim:
    lr: 0.0001

# Dataset parameters
dataset:
  DATA_PATH: './data'  # Path to the data directory
  test_ratio: 0.3
  batch_size: 64
  response_filename: 'processed_response_enR'  # Filename containing response labels
  img_foldername: 'Img_Denoised'
